extends RefCounted

const TEXT: Dictionary = {
"tagline": ["ĐƯỜNG ĐI TRỞ THÀNH VŨ KHÍ", "YOUR PATH BECOMES YOUR WEAPON"],
"start": ["BẮT ĐẦU", "START RUN"], "practice": ["Tập luyện · 5 phút", "Practice · 5 minutes"],
"settings": ["Thiết lập", "Settings"], "help": ["Cách chơi", "How to play"], "back": ["Trở lại", "Back"],
"pause": ["Tạm dừng", "Pause"], "resume": ["Tiếp tục", "Resume"], "restart": ["Chơi lại", "Restart"],
"home": ["Về menu", "Main menu"], "quit": ["Thoát game", "Quit"], "choose": ["CHỌN NÂNG CẤP", "CHOOSE AN UPGRADE"],
"win": ["ĐÃ PHÁ VỠ VÒNG LẶP", "LOOP BROKEN"], "lose": ["VÒNG LẶP KẾT THÚC", "LOOP ENDED"],
"volume": ["Âm lượng chính", "Master volume"], "music": ["Nhạc nền", "Music"], "sfx": ["Hiệu ứng âm thanh", "Sound effects"], "reduced": ["Giảm hiệu ứng", "Reduce effects"],
"shake": ["Rung màn hình", "Screen shake"], "haptics": ["Phản hồi rung", "Haptics"], "contrast": ["Tương phản cao", "High contrast"],
"language": ["Ngôn ngữ / Language", "Language / Ngôn ngữ"], "circuit_closed": ["VÒNG MẠCH KHÉP KÍN", "TIME CIRCUIT CLOSED"],
"boss": ["KẺ CANH GIỮ VÒNG LẶP", "THE LOOP WARDEN"],
"record": ["GHI", "REC"], "kills": ["Hạ gục", "Kills"], "time": ["Thời gian", "Time"],
"hint": ["Chạm và rê ở bất kỳ đâu trong đấu trường · Tự bắn · Chạm nút tạm dừng", "Touch and drag anywhere in the arena · Auto fire · Tap pause"],
"help_body": ["Kéo ngón tay để di chuyển và để lại đường ký ức. Chạy cắt qua một đoạn đường cũ để khép vòng mạch. Kẻ địch bên trong bị khóa thời gian và vũ khí kích hoạt đòn kết liễu riêng. Vòng nhỏ nhanh, vòng lớn mạnh nhưng nguy hiểm.\n\nAstria tự bắn mục tiêu gần nhất. Thu XP để chọn nâng cấp. Hạ năm boss của Neon Ruins để thắng.", "Drag to move and leave a memory trail. Cross an older segment to close a Time Circuit. Enemies inside are time-locked and your weapon triggers its unique finisher. Small loops are quick; large loops are stronger but riskier.\n\nAstria auto-fires at the nearest target. Collect XP for upgrades. Defeat all five Neon Ruins bosses to win."],
"ready": ["Đã hiểu · Vào trận", "Got it · Enter arena"],
"save_failed": ["Không lưu được dữ liệu. Kiểm tra quyền ghi và dung lượng đĩa.", "Could not save. Check disk space and write permissions."],
"save_recovered": ["Đã phục hồi dữ liệu từ bản sao lưu.", "Profile recovered from backup."],
"save_reset": ["Dữ liệu lưu không hợp lệ; đang dùng thiết lập mặc định.", "Invalid save data; using defaults."],
"records": ["%d trận  /  %d thắng  /  %d hạ gục", "%d runs  /  %d wins  /  %d kills"],
"profile": ["HỒ SƠ", "PROFILE"], "play": ["CHƠI", "PLAY"], "armory": ["KHO VŨ KHÍ", "ARMORY"], "meta_upgrades": ["NÂNG CẤP", "UPGRADES"],
"meta_hp": ["Máu tối đa +15", "Max HP +15"], "meta_damage": ["Sát thương +5%", "Weapon damage +5%"], "meta_armor": ["Giáp +1", "Armor +1"], "meta_haste": ["Tốc độ bắn +5%", "Fire rate +5%"],
"level_word": ["Cấp", "Level"], "upgrade_action": ["NÂNG CẤP", "UPGRADE"], "select": ["CHỌN", "SELECT"], "selected": ["ĐANG DÙNG", "SELECTED"],
"pulse_finisher": ["Bắn nhanh · Dẫn điện qua mục tiêu trong vòng mạch.", "Rapid fire · Chains lightning through circuit targets."],
"scatter_finisher": ["Bắn chùm · Hội tụ sát thương về tâm vòng mạch.", "Spread fire · Converges damage toward the circuit center."],
"lance_finisher": ["Bắn xuyên · Laser viền và pulse sụp về tâm.", "Piercing fire · Perimeter laser collapses inward."],
"weapon_locked_0": ["Có sẵn", "Available"], "weapon_locked_1": ["Khóa · Hạ boss level 2", "Locked · Defeat level 2 boss"], "weapon_locked_2": ["Khóa · Thắng một run", "Locked · Win one run"],
"reset_tutorial": ["Đặt lại hướng dẫn", "Reset tutorial"], "credits": ["Ghi công & giấy phép", "Credits & licenses"], "reset_progress": ["Xóa tiến trình", "Reset progress"],
"reset_warning_1": ["Thao tác này xóa vàng, lõi, nâng cấp và mở khóa vũ khí. Thiết lập sẽ được giữ.", "This removes currency, upgrades and weapon unlocks. Settings are preserved."],
"reset_confirm_title": ["Xác nhận lần cuối", "Final confirmation"], "reset_warning_2": ["Không thể hoàn tác tiến trình sau khi xóa.", "Progress cannot be restored after reset."],
"credits_body": ["Replayborn · Godot 4.7.2\nThiết kế và code gốc trong repository. Art original_v1 có hồ sơ nguồn trong docs/ASSET_PROVENANCE.md. Nhạc Tense Future Loop của gmason, CC0. Font Cascadia Code cần được xác minh lại trong release checklist.", "Replayborn · Godot 4.7.2\nOriginal design and code in this repository. original_v1 art provenance is recorded in docs/ASSET_PROVENANCE.md. Tense Future Loop by gmason, CC0. Cascadia Code licensing must be reverified in the release checklist."],
"weapon": ["CHỌN VŨ KHÍ", "CHOOSE WEAPON"], "pulse": ["Xung lực", "Pulse"], "scatter": ["Tán xạ", "Scatter"], "lance": ["Xuyên phá", "Lance"],
"memory": ["KÝ ỨC", "MEMORY"], "memory_ready": ["SẴN SÀNG", "READY"],
"chrono_shift": ["CHRONO SHIFT", "CHRONO SHIFT"], "chrono_ready": ["SẴN SÀNG", "READY"], "combo": ["COMBO", "COMBO"], "overdrive": ["QUÁ TẢI", "OVERDRIVE"],
"run_status": ["TRẠNG THÁI RUN", "RUN STATUS"], "system_brand": ["HỆ THỐNG / REPLAYBORN", "SYSTEM / REPLAYBORN"],
"sound_section": ["ÂM THANH", "AUDIO"], "experience_section": ["TRẢI NGHIỆM", "EXPERIENCE"],
"level_up": ["LÊN CẤP", "LEVEL UP"], "offline": ["NGOẠI TUYẾN", "OFFLINE"],
"boss_hp": ["BOSS / %s   %d / %d MÁU", "BOSS / %s   %d / %d HP"],
"run_dock": ["BẾN KHỞI HÀNH", "RUN DOCK"],
"menu_status": ["5 LEVEL · 5 BOSS · NGOẠI TUYẾN", "5 LEVELS · 5 BOSSES · OFFLINE"],
"runner_ready": ["NGƯỜI CHẠY MẠCH · SẴN SÀNG", "CIRCUIT RUNNER · READY"],
"boss_arrives": ["CẢNH BÁO · BOSS CỦA MỨC ĐỘ %d", "WARNING · LEVEL %d BOSS"],
"level_cleared": ["ĐÃ HẠ BOSS · MỞ KHÓA MỨC ĐỘ %d", "BOSS DEFEATED · LEVEL %d UNLOCKED"],
"stage": ["GIAI ĐOẠN %d", "PHASE %d"], "result": ["%02d:%02d  ·  %d hạ gục", "%02d:%02d  ·  %d kills"],
"abandon": ["Rời trận hiện tại? Tiến trình trận sẽ mất.", "Leave this run? Current run progress will be lost."],
"confirm": ["Đồng ý", "Confirm"], "cancel": ["Hủy", "Cancel"],
"pause_note": ["Đường ký ức hiện tại được giữ nguyên khi tạm dừng.", "The current memory trail is preserved while paused."],
"circuit_result": ["Level %d · %d vòng mạch · %d mục tiêu bị bắt · %d boss\n◆ %d vàng · ◈ %d lõi", "Level %d · %d circuits · %d targets captured · %d bosses\n◆ %d gold · ◈ %d cores"],
"combat_result": ["COMBO cao nhất %d%% · %d sát thương", "MAX COMBO %d%% · %d damage"],
"paused_kicker": ["ĐÃ TẠM DỪNG · PHIÊN AN TOÀN", "RUN PAUSED · SESSION SAFE"],
"confirm_kicker": ["CẦN XÁC NHẬN", "CONFIRMATION REQUIRED"],
"abandon_note": ["Kết thúc phiên sẽ xóa tiến trình trong trận hiện tại.", "Ending the session discards current run progress."],
"settings_kicker": ["CẤU HÌNH HỆ THỐNG", "SYSTEM CONFIGURATION"],
"manual_kicker": ["SỔ TAY THỰC ĐỊA", "FIELD MANUAL"],
"tutorial_kicker": ["TÓM TẮT NHIỆM VỤ", "MISSION BRIEFING"],
"tutorial_intro": ["Kéo để di chuyển. Đường màu cyan là Ký ức của Astria. Hãy chạy cắt lại một đoạn đường cũ để khép Vòng mạch.", "Drag to move. The cyan line is Astria's Memory. Cross an older trail segment to close a Time Circuit."],
"skip_tutorial": ["BỎ QUA HƯỚNG DẪN", "SKIP TUTORIAL"],
"tutorial_move": ["KÉO ĐỂ DI CHUYỂN · TẠO ĐƯỜNG KÝ ỨC", "DRAG TO MOVE · DRAW A MEMORY TRAIL"],
"tutorial_circuit": ["BAO QUANH MỤC TIÊU · CẮT ĐƯỜNG CŨ", "ENCIRCLE TARGETS · CROSS THE OLD TRAIL"],
"tutorial_complete_title": ["VÒNG MẠCH HOÀN TẤT", "CIRCUIT COMPLETE"],
"tutorial_complete": ["Kẻ địch bên trong bị khóa thời gian và vũ khí tự kích hoạt Kết liễu. Trong run, thu XP để chọn một trong ba Nâng cấp.", "Captured enemies are time-locked and your weapon triggers its Finisher. During a run, collect XP to choose one of three Upgrades."],
"choose_core": ["CHỌN LÕI", "CHOOSE CORE"],
"upgrade_kicker": ["LÊN CẤP · CHỌN MỘT LÕI", "LEVEL UP · SELECT ONE CORE"],
"upgrade_note": ["Bạn đã nhặt đủ XP. Chạm một lõi để nâng cấp vòng lặp.", "You collected enough XP. Tap a core to upgrade this run."],
"core_index": ["LÕI %02d", "CORE %02d"], "tap_select": ["CHẠM VÀO THẺ ĐỂ CHỌN", "TAP THE CARD TO SELECT"],
"upgrade_offense": ["TẤN CÔNG", "OFFENSE"], "upgrade_circuit": ["MẠCH THỜI GIAN", "TIME CIRCUIT"], "upgrade_survival": ["SINH TỒN", "SURVIVAL"], "upgrade_weapon": ["VŨ KHÍ", "WEAPON"],
"relic_resonance": ["DI VẬT · CỘNG HƯỞNG", "RELIC · RESONANCE"], "relic_momentum": ["DI VẬT · XUNG LỰC", "RELIC · MOMENTUM"], "relic_vitality": ["DI VẬT · SỨC SỐNG", "RELIC · VITALITY"],
"relic_result": ["DI VẬT: %s", "RELICS: %s"],
"result_kicker": ["BÁO CÁO RUN · KHO MẠCH", "RUN REPORT · CIRCUIT ARCHIVE"]
}

static func dict_value(source: Dictionary, key: Variant, fallback: Variant) -> Variant:
	return source[key] if source.has(key) else fallback

static func get_text(key: String, language: String = "vi") -> String:
	var pair: Array = dict_value(TEXT, key, [key, key])
	return pair[1 if language == "en" else 0]
